apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: tile-server
spec:
  encryptedData:
    db: AgDZOzzQE0QLfmQGsb1f2z0yQwQTBwT2Svgf/FxV25hP5z8UJ4u7sKM8Ny80bmkeHHRql4Ikp9d3117zPClhg1nlyLrLHAlMfq8Qi6q2dJP5uFyvqGw8xYrc9Pm0GQsED/KlEgHifDVMby3pI1eDj8sYDWWLfInn4ZC/Pphu/b/NrHa4JTYn/RMLXtHoCfVnmI75kaR64Y6pgzqW/RTAuV+1GD8VhiSlutY2bokEXwba4hwx8Z3S1QYa5z35MLFotz42Ggbg82m700ZTRFV3I3SqDBrGl0SglRAIUZx/FRYtfyHRuqd0+YmCn38pFYEH6FuhdM/8eHpsiwvNxf7yJPWs48697dcl8faDKRGzo+5kyUwFL9tSALO8c/glAqflybuzdJdf/Lmfwa1y72JVBzWPll7iSzSZlLdYClXdPrqLP9qogyBM+lQVOm2X/SZPQ9ZE/52U2MaozZnAjm07L0wXpPdoiAQzcbW7HgFQg3WG/ioO9ikRWsUUJpgRjNKnw7wBE5yORTt5LHIe6kFBOQZUGScv+WeBMSbBogXVIlCG5+mpgAjbIpSsJ/0n4C2O3whV7sKVPNQmwMkFyHFh+tOZfdtBZBIbfvXaMo5J1FsxhTkLp64v5qsVwdLvZRu3mTh8Agp8Jz6Q5ftfLCWoYMw9ll1nGz87ekvDyHwq2ALpaYRQPS1bm1XGsbtq2Z++furuvxDVPzCvFpYHcdxARLOE4oZi5symmOVjzxJkpw7JlirrjrjRx+ONiUBr0N8v7cXUgxY6D0mQevI6SW5/GXL8AXKdptNL+bcYcsqx4yVABCrDygBu5x03yc2/m0SmIFoPDPSp54o/8bFdn1SMB5xkmskB5DXdg6Sl5yIPWJXVxxb1Fn8HrRzSzcFTxn/WvuK3Q1Q=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: tile-server

