apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-tile-server
  labels:
    app: treetracker-tile-server
spec:
  replicas: 6
  template:
    spec:
      containers:
        - name: treetracker-tile-server
          env:
            - name: PORT
              value: "3000"
            - name: PG_POOL_SIZE
              value: "20"
            - name: CACHE_SIZE
              value: "10000"
            - name: CACHE_EXPIRE
              value: "60000"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: MAXIMUM_ZOOM_LEVEL_USING_GLOBAL_DATASET
              value: "15"
            - name: MAXIMUM_ZOOM_LEVEL_HANDLING_ZOOM_TARGET
              value: "6"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: database-connection
                  key: db
