apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-tile-server
spec:
  timeout_ms: 0
  cors:
    origins:
      - https://prod-k8s.treetracker.org
    methods: GET
    headers:
      - Content-Type
      - Authorization
