apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: tile-server
spec:
  encryptedData:
    db: AgB4Y5wqUdgDGd57hpmpB6l8000fnK/UmAADRoeOw1qO1dLdINnx8MoQkT/hNfVPnZoYMe8tIU6hmLnPqfaXySRJR0N4NBJtqFVNAswEUQCIAC7rKYScMp63Ex+A+SJBJNrWD/bM2OM0sVwSoivWsRGSdE2rXNRt+1ifDnDaX5vAYgSdo/pFB+0EOV89+V4YKSoxUVQR+R/iqcnydnzFAjWJ6T96J/LYdHiMcjjG0daBfjFN4HfvQIUQpfzYT23Z6DjXmjeLNvmx7Ma9IQjTDrFc/XJzyjCn8Ia4FuizNLPkMmczN+PScM9KADmqbu++l0nVGwlJJSSLDzhydW4t9ye+CIV1cDz45W5IAJE+2CdXYhXp7B5MzieuZ//XiNsiMu09tQdZ2YzaUGz3Wp+hdWpS5NgRIAFrCvmiTfEekHBVrcwy64+XgPFUfSn5S7hBv09kr5suIAuKZ+iYKYbUmrVH1mU+KiTeo581WcMHFnmxB0afWGMNSGg4PL3jJ4w4knY4JX3NR1JYNbl/kIDoIg0FJ9enlv/dI87zEfJTJj6bd8VQd0G4IN4cgb4OQEHA1guJgp9+83+DWgfCTJ9Inat7CaR70AR6Dz3ob3ZLZP+zDujSKQwgjLlSziK/r+vq5WDmgpeB0QeF/hwjhOjkb9tycnQqKUQsGjBhmZVQeuGXRU/EIO/+l8OYpovZlPB+zBUlSaslSCe3cqbwRwwFOtGJPhqUSRSFf1SPXMI5ZPE4DD/wEDfZ4wncJQOMChzSGjWV03UQDnVCNhpm9yVmXiKpeYC7DrK1TGkdpbeRICp+jy/7Num0E3KYQr+BCkvAmjOaZOTwZgicU8yneFzG/HiuKVoUtyHN/024Xc8edwkh8JS4xSzeqsRV9jNLeQ==
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: tile-server

