apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: tile-server
spec:
  encryptedData:
    db: AgBu4U3bGlpf+t/5EP2G7gU6/lQ6Z+N/nCjYtgU3kMWmR+TUuFt5sfSvbvE0TO9ohKxM3eIxZAvmT2Q6wfrZAqCel9VLAMWqOIRgtKAGhB4jhutC9s9TGx74DMDXKkzXFGQPpRfMf92QJpKGc1mpWJoviTcYdtqNqdqFVXFuJhs2cLA2H2Xu/nl5Vkq7XG8oUFVcdXnc0uNoOuDcwxWlqquBrjh6XTccODWRcJZRhVLzATKmYSVjCJUqzXERWq9T6p65rqPTKyqJNycD9wtwnEyepSIzckI0HWWt+yE5RmJBNcSZ4mvlQqQJ+dz+0N96lCnkv7ssM659RXsATEJiAfOoy8bV77sud8TMunE4BYnOnijT8wf52CCiS4+W540BCkOP9/obvBpxzBbQqicx/mg5L0qjoHgX3XMLYRzP9TI+YGwqEp8QtkGyRWFh/EM5pO9A4i2EZkveA2UL1GSSx8XIs0UYIUeYVeTneKvz5OdEzD6dt+v6jD9bhQ6WDUfaqK8pbe7Q47PIuxJcGWJ7H0VBJLGWRYjt8KihjWnSER3Uz3tk/Il+J03Cv0vkG3EMSz9+E1CxD9bXdaB4DuRiz25QO734pGF63M3y4wzWJdW5cNoeLnysobWr9mGTmS0vLpU//3BhH1ueX1/kH9uWbe/eHrFgyjAhXoB/EFAHBIr5IfZV9cLSisy5xC+ngxIUkOQ=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: tile-server

