apiVersion: v1
kind: Service
metadata:
  name: treetracker-tile-server
spec:
  selector:
    app: treetracker-tile-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
