
name: Deploy to Production Env

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: "tag"
        required: true

env: 
  project-directory: ./

jobs:
  deploy-test:
    name: Deploy selected tag to production environment, requires approval
    runs-on: ubuntu-latest
    if: |
      github.repository == 'Greenstand/node-mapnik-1'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-tag }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./
      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      - name: Run kustomize
        run: (cd deployment/base && ../../kustomize edit set image greenstand/treetracker-map-tile-server:${{ steps.package-version.outputs.current-version }} )
      - name: Install doctl for kubernetes
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_PRODUCTION_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.PRODUCTION_CLUSTER_NAME }}
      - name: Update kubernetes resources
        run: kustomize build deployment/overlays/production | kubectl apply -n tile-server --wait -f -
